version: '3.8'
services:
  janus:
    platform: linux/amd64 # 通过环境变量控制平台，macOS 可设为 linux/amd64，Linux 可留空
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: janus-local:latest
    privileged: true
    network_mode: "host" # is not reliable on Docker Desktop for macOS
    # ports:
    #   - "8088:8088"
    #   - "8188:8188"
    #   - "7088:7088"
    #   - "8888:8888"
      # - "60000-63000:60000-63000/udp"
    volumes:
      - ./:/janus:rw       # mount repository root into container so code is shared with host
    working_dir: /janus
    restart: unless-stopped